apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-app
  template:
    metadata:
      labels:
        app: nodejs-app
    spec:
      containers:
      - name: nodejs-app
        image: sofienazzabi/nodejs-app:57  # Using the auto-increment version
        ports:
        - containerPort: 4000  # Match the exposed port from Dockerfile

---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-app
spec:
  selector:
    app: nodejs-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4000
      nodePort: 30001  # Expose on port 30001 of every node
  type: NodePort  # Use NodePort for external access
