# Add additional ArgoCD components (e.g., controller, repo-server, application controller)
# The full official manifest is available at:
# https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-app
  template:
    metadata:
      labels:
        app: nodejs-app
    spec:
      containers:
      - name: nodejs-app
        image: sofienazzabi/nodejs-app:44  # Using the auto-increment version
        ports:
        - containerPort: 4000  # Match the exposed port from Dockerfile

---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-app
spec:
  selector:
    app: nodejs-app
  ports:
    - protocol: TCP
      port: 80  # Expose service on port 80
      targetPort: 4000  # Forward to the container's exposed port
  type: LoadBalancer  # Use LoadBalancer for external access
