name: Deploy AKS Cluster

on:
  push:
    branches:
      - main  # Déclenche le pipeline à chaque push sur la branche principale

jobs:
  terraform:
    runs-on: ubuntu-latest  # Utilise un environnement Ubuntu pour le pipeline

    steps:
      # 1. Checkout le code du dépôt
      - name: Checkout code
        uses: actions/checkout@v2

      # 2. Installer Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2

      # 3. Installer Azure CLI (remplace l'ancienne action avec azure/cli-action)
      - name: Set up Azure CLI
        uses: azure/cli-action@v1  # Version mise à jour de l'action Azure CLI

      # 4. Se connecter à Azure avec les secrets GitHub
      - name: Login to Azure
        run: |
          az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}
          az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # 5. Initialiser Terraform
      - name: Terraform Init
        run: terraform init

      # 6. Appliquer la configuration Terraform pour créer le cluster
      - name: Terraform Apply
        run: terraform apply -auto-approve
